# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75b37978977ad1e9d8c4e0cdb3598b4c233c803f10abf01ac09749a4797c613df66c09f2247d31815e9dd804a421ea96ba5821270f524637671421d693f59227

test:
  secret_key_base: 98e95786eb4a3155e70524fedeaccbce2cda1770e7933f78dfc1ce0375a63ea0661278d347d4e1d2d92de6b38bffdfbb8d97e5ed73aa6c6156bfcb17c5f66961

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
